services:
  db.cardapio:
    image: mysql:9
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: GTT188#
      MYSQL_DATABASE: cardapio
    ports:
    - '3307:3306'
    volumes:
      - mysql.cardapio:/var/lib/mysql
volumes:
  mysql.cardapio:
  
